BROKERS = [
    {"code": "1", "name": "Kumari Securities Private Limited", "phone": "4423689", "districts": ["Kathmandu", "Baglung"], "tms_link": "tms01.nepsetms.com.np", "branch_count": 2, "active_status": "A", "is_dealer": False, "avg_rating": 4, "total_ratings": 4, "thirty_days_turnover": 2329638732.01, "latest_turnover": 55950958.1, "today_total_amount": None, "today_buy_amount": None, "today_sell_amount": None, "today_buy_qty": None, "today_sell_qty": None},
    {"code": "3", "name": "Arun Securities (PVT) Ltd.", "phone": "016916470", "districts": ["Kathmandu"], "tms_link": "tms03.nepsetms.com.np", "branch_count": 1, "active_status": "A", "is_dealer": False, "avg_rating": 5, "total_ratings": 3, "thirty_days_turnover": 1687125316.24, "latest_turnover": 55301099.3, "today_total_amount": None, "today_buy_amount": None, "today_sell_amount": None, "today_buy_qty": None, "today_sell_qty": None},
    {"code": "4", "name": "Opal Securities Investment (PVT) Ltd.", "phone": "4239273", "districts": ["Kathmandu"], "tms_link": "tms04.nepsetms.com.np", "branch_count": 1, "active_status": "A", "is_dealer": False, "avg_rating": 4.82, "total_ratings": 17, "thirty_days_turnover": 5944681445.6, "latest_turnover": 210957440.2, "today_total_amount": 210957440.2, "today_buy_amount": 100367270.7, "today_sell_amount": 110590169.5, "today_buy_qty": 177321, "today_sell_qty": 203006},
    {"code": "5", "name": "Market Securities & Exchange (PVT) Ltd.", "phone": "4248973", "districts": ["Kathmandu"], "tms_link": "tms05.nepsetms.com.np", "branch_count": 1, "active_status": "A", "is_dealer": False, "avg_rating": 5, "total_ratings": 0, "thirty_days_turnover": 1280146860.46, "latest_turnover": 28281742.8, "today_total_amount": None, "today_buy_amount": None, "today_sell_amount": None, "today_buy_qty": None, "today_sell_qty": None},
    {"code": "6", "name": "Agrawal Securities (PVT) Ltd.", "phone": "4424657", "districts": ["Kathmandu", "Morang", "Dhanusa", "Rupandehi"], "tms_link": "tms06.nepsetms.com.np", "branch_count": 4, "active_status": "A", "is_dealer": False, "avg_rating": 4.59, "total_ratings": 22, "thirty_days_turnover": 5563890839.2, "latest_turnover": 102119839.55, "today_total_amount": None, "today_buy_amount": None, "today_sell_amount": None, "today_buy_qty": None, "today_sell_qty": None},
    {"code": "7", "name": "J.F. Securites (PVT) Ltd.", "phone": "4442912", "districts": ["Kathmandu", "Rupandehi", "Dang", "Jhapa"], "tms_link": "tms07.nepsetms.com.np", "branch_count": 4, "active_status": "A", "is_dealer": False, "avg_rating": 5, "total_ratings": 2, "thirty_days_turnover": 1894457812.91, "latest_turnover": 41786888, "today_total_amount": None, "today_buy_amount": None, "today_sell_amount": None, "today_buy_qty": None, "today_sell_qty": None},
    {"code": "8", "name": "Brilliant Securities Pvt. Ltd.", "phone": "015970780", "districts": ["Kathmandu", "Sunsari", "Siraha"], "tms_link": "tms08.nepsetms.com.np", "branch_count": 3, "active_status": "A", "is_dealer": False, "avg_rating": 2.75, "total_ratings": 4, "thirty_days_turnover": 1901745302.61, "latest_turnover": 37688801.85, "today_total_amount": None, "today_buy_amount": None, "today_sell_amount": None, "today_buy_qty": None, "today_sell_qty": None},
    {"code": "10", "name": "Pragyan Securities (PVT) Ltd.", "phone": "016226890", "districts": ["Kathmandu", "Morang"], "tms_link": "tms10.nepsetms.com.np", "branch_count": 2, "active_status": "A", "is_dealer": False, "avg_rating": 5, "total_ratings": 0, "thirty_days_turnover": 1072256911.05, "latest_turnover": 22186739.14, "today_total_amount": None, "today_buy_amount": None, "today_sell_amount": None, "today_buy_qty": None, "today_sell_qty": None},
    {"code": "11", "name": "Malla & Malla Stock Broking Company Pvt. Limited", "phone": "4432088", "districts": ["Kathmandu", "Ilam", "Panchthar"], "tms_link": "tms11.nepsetms.com.np", "branch_count": 3, "active_status": "A", "is_dealer": False, "avg_rating": 4.3, "total_ratings": 10, "thirty_days_turnover": 1127872534.05, "latest_turnover": 28535741.3, "today_total_amount": None, "today_buy_amount": None, "today_sell_amount": None, "today_buy_qty": None, "today_sell_qty": None},
    {"code": "13", "name": "Thrive Brokerage House Pvt. Ltd", "phone": "4419051", "districts": ["Kathmandu", "Baglung", "Tanahu"], "tms_link": "tms13.nepsetms.com.np", "branch_count": 3, "active_status": "A", "is_dealer": False, "avg_rating": 3.83, "total_ratings": 6, "thirty_days_turnover": 2007332666.66, "latest_turnover": 58323752.449999996, "today_total_amount": None, "today_buy_amount": None, "today_sell_amount": None, "today_buy_qty": None, "today_sell_qty": None},
    {"code": "14", "name": "Nepal Stock House (PVT) Ltd.", "phone": "4265888", "districts": ["Kathmandu", "Baglung"], "tms_link": "tms14.nepsetms.com.np", "branch_count": 2, "active_status": "A", "is_dealer": False, "avg_rating": 5, "total_ratings": 3, "thirty_days_turnover": 4973924350.33, "latest_turnover": 112308419.5, "today_total_amount": None, "today_buy_amount": None, "today_sell_amount": None, "today_buy_qty": None, "today_sell_qty": None},
    {"code": "16", "name": "Primo Securities (PVT) Ltd.", "phone": "4168214", "districts": ["Kathmandu", "Parsa", "Chitwan", "Banke"], "tms_link": "tms16.nepsetms.com.np", "branch_count": 4, "active_status": "A", "is_dealer": False, "avg_rating": 4.67, "total_ratings": 6, "thirty_days_turnover": 3154062035.17, "latest_turnover": 49033095.5, "today_total_amount": None, "today_buy_amount": None, "today_sell_amount": None, "today_buy_qty": None, "today_sell_qty": None},
    {"code": "17", "name": "ABC Securities Private Limited", "phone": "4230787", "districts": ["Kathmandu", "Sunsari", "Parsa"], "tms_link": "tms17.nepsetms.com.np", "branch_count": 3, "active_status": "A", "is_dealer": False, "avg_rating": 5, "total_ratings": 4, "thirty_days_turnover": 4731771382.96, "latest_turnover": 144409617.3, "today_total_amount": None, "today_buy_amount": None, "today_sell_amount": None, "today_buy_qty": None, "today_sell_qty": None},
    {"code": "18", "name": "Sagarmatha Securities Private Limited", "phone": "4433221", "districts": ["Kathmandu"], "tms_link": "tms18.nepsetms.com.np", "branch_count": 1, "active_status": "A", "is_dealer": False, "avg_rating": 5, "total_ratings": 2, "thirty_days_turnover": 629820221.4, "latest_turnover": 16993542.2, "today_total_amount": None, "today_buy_amount": None, "today_sell_amount": None, "today_buy_qty": None, "today_sell_qty": None},
    {"code": "19", "name": "Nepal Investment And Securities Trading Private Limited", "phone": "4495450", "districts": ["Kathmandu", "Morang"], "tms_link": "tms19.nepsetms.com.np", "branch_count": 2, "active_status": "A", "is_dealer": False, "avg_rating": 3, "total_ratings": 1, "thirty_days_turnover": 1738109672.34, "latest_turnover": 35470103.44, "today_total_amount": None, "today_buy_amount": None, "today_sell_amount": None, "today_buy_qty": None, "today_sell_qty": None},
    {"code": "20", "name": "Sipla Securities Private Limited", "phone": "4255782", "districts": ["Kathmandu"], "tms_link": "tms20.nepsetms.com.np", "branch_count": 1, "active_status": "A", "is_dealer": False, "avg_rating": 1, "total_ratings": 4, "thirty_days_turnover": 1175928268.62, "latest_turnover": 27396399.3, "today_total_amount": None, "today_buy_amount": None, "today_sell_amount": None, "today_buy_qty": None, "today_sell_qty": None},
    {"code": "21", "name": "Midas Stock Broking Company Private Limited", "phone": "4240089", "districts": ["Kathmandu", "Rupandehi", "Gorkha"], "tms_link": "tms21.nepsetms.com.np", "branch_count": 3, "active_status": "A", "is_dealer": False, "avg_rating": 2, "total_ratings": 7, "thirty_days_turnover": 2946783879.82, "latest_turnover": 94262180.4, "today_total_amount": None, "today_buy_amount": None, "today_sell_amount": None, "today_buy_qty": None, "today_sell_qty": None},
    {"code": "22", "name": "Siprabi Securities Pvt. Ltd.", "phone": "5530701", "districts": ["Kathmandu", "Parsa"], "tms_link": "tms22.nepsetms.com.np", "branch_count": 3, "active_status": "A", "is_dealer": False, "avg_rating": 5, "total_ratings": 3, "thirty_days_turnover": 2541700283.53, "latest_turnover": 59960864.3, "today_total_amount": None, "today_buy_amount": None, "today_sell_amount": None, "today_buy_qty": None, "today_sell_qty": None},
    {"code": "25", "name": "Sweta Securities Private Limited", "phone": "4444791", "districts": ["Kathmandu"], "tms_link": "tms25.nepsetms.com.np", "branch_count": 1, "active_status": "A", "is_dealer": False, "avg_rating": 4.8, "total_ratings": 5, "thirty_days_turnover": 3592844951.14, "latest_turnover": 62973647.9, "today_total_amount": None, "today_buy_amount": None, "today_sell_amount": None, "today_buy_qty": None, "today_sell_qty": None},
    {"code": "26", "name": "Asian Securities Private Ltd.", "phone": "014524351", "districts": ["Kathmandu", "Rupandehi"], "tms_link": "tms26.nepsetms.com.np", "branch_count": 2, "active_status": "A", "is_dealer": False, "avg_rating": 4, "total_ratings": 2, "thirty_days_turnover": 3104662812.45, "latest_turnover": 59729463.8, "today_total_amount": None, "today_buy_amount": None, "today_sell_amount": None, "today_buy_qty": None, "today_sell_qty": None},
    {"code": "28", "name": "Shree Krishna Securities Ltd.", "phone": "4224262", "districts": [], "tms_link": "tms28.nepsetms.com.np", "branch_count": 0, "active_status": "A", "is_dealer": False, "avg_rating": 5, "total_ratings": 1, "thirty_days_turnover": 4037695907.61, "latest_turnover": 119667345, "today_total_amount": None, "today_buy_amount": None, "today_sell_amount": None, "today_buy_qty": None, "today_sell_qty": None},
    {"code": "29", "name": "Trisul Securities & Invt. Ltd.", "phone": "4440709", "districts": ["Kathmandu", "Chitwan", "Nawalparasi(Purba)"], "tms_link": "tms29.nepsetms.com.np", "branch_count": 3, "active_status": "A", "is_dealer": False, "avg_rating": 3.62, "total_ratings": 13, "thirty_days_turnover": 2579082759.31, "latest_turnover": 38878800.4, "today_total_amount": None, "today_buy_amount": None, "today_sell_amount": None, "today_buy_qty": None, "today_sell_qty": None},
    {"code": "32", "name": "Premier Securities Company Ltd.", "phone": "4432700", "districts": ["Kathmandu", "Baglung", "Syangja"], "tms_link": "tms32.nepsetms.com.np", "branch_count": 3, "active_status": "A", "is_dealer": False, "avg_rating": 5, "total_ratings": 6, "thirty_days_turnover": 5079425940.6, "latest_turnover": 90210371.25, "today_total_amount": None, "today_buy_amount": None, "today_sell_amount": None, "today_buy_qty": None, "today_sell_qty": None},
    {"code": "33", "name": "Dakshinkali Investment & Securities Pvt. Ltd.", "phone": "4168640", "districts": ["Kathmandu", "Rupandehi"], "tms_link": "tms33.nepsetms.com.np", "branch_count": 2, "active_status": "A", "is_dealer": False, "avg_rating": 5, "total_ratings": 7, "thirty_days_turnover": 4063717377.15, "latest_turnover": 204726159.6, "today_total_amount": 204726159.6, "today_buy_amount": 37530561.9, "today_sell_amount": 167195597.7, "today_buy_qty": 83128, "today_sell_qty": 404633},
    {"code": "34", "name": "Vision Securities Pvt. Ltd", "phone": "4770452", "districts": ["Kathmandu", "Kavrepalanchowk", "Rupandehi", "Nawalparasi(Purba)", "Myagdi", "Tanahu", "Kaski", "Kapilvastu", "Ilam", "Lalitpur", "Kailali", "Bhaktapur"], "tms_link": "tms34.nepsetms.com.np", "branch_count": 12, "active_status": "A", "is_dealer": False, "avg_rating": 1.81, "total_ratings": 36, "thirty_days_turnover": 6725824482.89, "latest_turnover": 231014962.1, "today_total_amount": 231014962.1, "today_buy_amount": 80863089.4, "today_sell_amount": 150151872.7, "today_buy_qty": 178093, "today_sell_qty": 381650},
    {"code": "35", "name": "Kohinoor Investment & Securities Pvt. Ltd.", "phone": "4442858", "districts": ["Kathmandu", "Baglung"], "tms_link": "tms35.nepsetms.com.np", "branch_count": 2, "active_status": "A", "is_dealer": False, "avg_rating": 4.31, "total_ratings": 13, "thirty_days_turnover": 4686694743.37, "latest_turnover": 107615163.1, "today_total_amount": None, "today_buy_amount": None, "today_sell_amount": None, "today_buy_qty": None, "today_sell_qty": None},
    {"code": "36", "name": "Secured Securities Ltd.", "phone": "4168172", "districts": ["Kathmandu", "Jhapa"], "tms_link": "tms36.nepsetms.com.np", "branch_count": 3, "active_status": "A", "is_dealer": False, "avg_rating": 5, "total_ratings": 4, "thirty_days_turnover": 2961241656.89, "latest_turnover": 82413044.5, "today_total_amount": None, "today_buy_amount": None, "today_sell_amount": None, "today_buy_qty": None, "today_sell_qty": None},
    {"code": "37", "name": "Swarna Laxmi Securities Pvt. Ltd.", "phone": "430534", "districts": ["Kathmandu", "Makwanpur"], "tms_link": "tms37.nepsetms.com.np", "branch_count": 2, "active_status": "A", "is_dealer": False, "avg_rating": 5, "total_ratings": 1, "thirty_days_turnover": 779706588.82, "latest_turnover": 16146976.780000001, "today_total_amount": None, "today_buy_amount": None, "today_sell_amount": None, "today_buy_qty": None, "today_sell_qty": None},
    {"code": "38", "name": "Dipshikha Dhitopatra Karobar Co. Pvt Ltd.", "phone": "4102532", "districts": ["Kathmandu", "Kailali", "Kanchanpur", "Chitwan", "Dolkha", "Siraha", "Bhaktapur"], "tms_link": "tms38.nepsetms.com.np", "branch_count": 8, "active_status": "A", "is_dealer": False, "avg_rating": 3.52, "total_ratings": 21, "thirty_days_turnover": 5162599763.49, "latest_turnover": 144714587.35, "today_total_amount": None, "today_buy_amount": None, "today_sell_amount": None, "today_buy_qty": None, "today_sell_qty": None},
    {"code": "39", "name": "Sumeru Securities Pvt. Ltd.", "phone": "4444740", "districts": ["Kathmandu", "Jhapa", "Kaski", "Chitwan"], "tms_link": "tms39.nepsetms.com.np", "branch_count": 4, "active_status": "A", "is_dealer": False, "avg_rating": 5, "total_ratings": 2, "thirty_days_turnover": 4079729698.62, "latest_turnover": 111881309.30000001, "today_total_amount": None, "today_buy_amount": None, "today_sell_amount": None, "today_buy_qty": None, "today_sell_qty": None},
    {"code": "40", "name": "Creative Securities Pvt Ltd", "phone": "4168205", "districts": ["Kathmandu", "Kavrepalanchowk", "Palpa"], "tms_link": "tms40.nepsetms.com.np", "branch_count": 3, "active_status": "A", "is_dealer": False, "avg_rating": 5, "total_ratings": 1, "thirty_days_turnover": 1297283468.41, "latest_turnover": 62815290.6, "today_total_amount": None, "today_buy_amount": None, "today_sell_amount": None, "today_buy_qty": None, "today_sell_qty": None},
    {"code": "41", "name": "Linch Stock Market Ltd.", "phone": "4784567", "districts": ["Morang", "Rupandehi"], "tms_link": "tms41.nepsetms.com.np", "branch_count": 2, "active_status": "A", "is_dealer": False, "avg_rating": 4.35, "total_ratings": 17, "thirty_days_turnover": 6214646772.3, "latest_turnover": 127197401.9, "today_total_amount": None, "today_buy_amount": None, "today_sell_amount": None, "today_buy_qty": None, "today_sell_qty": None},
    {"code": "42", "name": "Sani Securities Company Ltd.", "phone": "4401006", "districts": ["Kathmandu", "Chitwan", "Kaski", "Nawalparasi(Purba)"], "tms_link": "tms42.nepsetms.com.np", "branch_count": 4, "active_status": "A", "is_dealer": False, "avg_rating": 4.66, "total_ratings": 29, "thirty_days_turnover": 9335066731.06, "latest_turnover": 198444309.4, "today_total_amount": 198444309.4, "today_buy_amount": 133396047.8, "today_sell_amount": 65048261.6, "today_buy_qty": 305616, "today_sell_qty": 143793},
    {"code": "43", "name": "South Asian Bulls Pvt. Ltd.", "phone": "4284785", "districts": ["Kathmandu", "Jhapa"], "tms_link": "tms43.nepsetms.com.np", "branch_count": 2, "active_status": "A", "is_dealer": False, "avg_rating": 5, "total_ratings": 5, "thirty_days_turnover": 2309619608.22, "latest_turnover": 82701778.9, "today_total_amount": None, "today_buy_amount": None, "today_sell_amount": None, "today_buy_qty": None, "today_sell_qty": None},
    {"code": "44", "name": "Dynamic Money Managers Securities Pvt. Ltd.", "phone": "4414522", "districts": ["Kathmandu", "Kavrepalanchowk", "Chitwan"], "tms_link": "tms44.nepsetms.com.np", "branch_count": 3, "active_status": "A", "is_dealer": False, "avg_rating": 5, "total_ratings": 2, "thirty_days_turnover": 6878195077.39, "latest_turnover": 221328150, "today_total_amount": 221328150, "today_buy_amount": 93481135.6, "today_sell_amount": 127847014.4, "today_buy_qty": 215748, "today_sell_qty": 308981},
    {"code": "45", "name": "Imperial Securities Company Pvt. Ltd.", "phone": "4231004", "districts": ["Kathmandu", "Banke", "Surkhet", "Dhading", "Bhaktapur", "Kaski"], "tms_link": "tms45.nepsetms.com.np", "branch_count": 6, "active_status": "A", "is_dealer": False, "avg_rating": 3.21, "total_ratings": 19, "thirty_days_turnover": 7940011123.1, "latest_turnover": 197540632.9, "today_total_amount": None, "today_buy_amount": None, "today_sell_amount": None, "today_buy_qty": None, "today_sell_qty": None},
    {"code": "46", "name": "Kalika Securities Pvt. Ltd.", "phone": "4430601", "districts": ["Kathmandu", "Banke", "Mahottari", "Rupandehi", "Sunsari"], "tms_link": "tms46.nepsetms.com.np", "branch_count": 5, "active_status": "A", "is_dealer": False, "avg_rating": 5, "total_ratings": 1, "thirty_days_turnover": 1155344752.9, "latest_turnover": 19849449.8, "today_total_amount": None, "today_buy_amount": None, "today_sell_amount": None, "today_buy_qty": None, "today_sell_qty": None},
    {"code": "47", "name": "Neev Securities Pvt. Ltd.", "phone": "4470464", "districts": ["Kathmandu", "Sunsari", "Sarlahi"], "tms_link": "tms47.nepsetms.com.np", "branch_count": 3, "active_status": "A", "is_dealer": False, "avg_rating": 3.33, "total_ratings": 6, "thirty_days_turnover": 2107646545.93, "latest_turnover": 56733601.1, "today_total_amount": None, "today_buy_amount": None, "today_sell_amount": None, "today_buy_qty": None, "today_sell_qty": None},
    {"code": "48", "name": "Trishakti Securities Public Limited", "phone": "05970148", "districts": ["Kathmandu", "Kaski", "Kanchanpur", "Makwanpur", "Lalitpur", "Kavrepalanchowk", "Rupandehi"], "tms_link": "tms48.nepsetms.com.np", "branch_count": 7, "active_status": "A", "is_dealer": False, "avg_rating": 3.14, "total_ratings": 7, "thirty_days_turnover": 6957426204.53, "latest_turnover": 197567575.64999998, "today_total_amount": None, "today_buy_amount": None, "today_sell_amount": None, "today_buy_qty": None, "today_sell_qty": None},
    {"code": "49", "name": "Online Securities Pvt. Ltd.", "phone": "014168298", "districts": ["Kathmandu", "Sunsari", "Nuwakot"], "tms_link": "tms49.nepsetms.com.np", "branch_count": 3, "active_status": "A", "is_dealer": False, "avg_rating": 4.46, "total_ratings": 24, "thirty_days_turnover": 10323811441.73, "latest_turnover": 739101063.6, "today_total_amount": 739101063.6, "today_buy_amount": 381969972.1, "today_sell_amount": 357131091.5, "today_buy_qty": 1592560, "today_sell_qty": 1464750},
    {"code": "50", "name": "Cristal Kanchanjanga Securites Pvt. Ltd.", "phone": "9851026960", "districts": ["Kathmandu", "Morang"], "tms_link": "tms50.nepsetms.com.np", "branch_count": 2, "active_status": "A", "is_dealer": False, "avg_rating": 5, "total_ratings": 5, "thirty_days_turnover": 2456544167.55, "latest_turnover": 102589950.80000001, "today_total_amount": None, "today_buy_amount": None, "today_sell_amount": None, "today_buy_qty": None, "today_sell_qty": None},
    {"code": "51", "name": "Oxford Securities Pvt. Ltd.", "phone": "9841382573", "districts": ["Kathmandu", "Chitwan", "Nawalparasi(Pashchim)"], "tms_link": "tms51.nepsetms.com.np", "branch_count": 3, "active_status": "A", "is_dealer": False, "avg_rating": 3.25, "total_ratings": 4, "thirty_days_turnover": 1984887476.84, "latest_turnover": 58599303, "today_total_amount": None, "today_buy_amount": None, "today_sell_amount": None, "today_buy_qty": None, "today_sell_qty": None},
    {"code": "52", "name": "Sundhara Securities Limited", "phone": "01-4212215, 4260174", "districts": ["Kathmandu", "Lamjung", "Bara", "Chitwan"], "tms_link": "tms52.nepsetms.com.np", "branch_count": 4, "active_status": "A", "is_dealer": False, "avg_rating": 4.22, "total_ratings": 9, "thirty_days_turnover": 3164255254.88, "latest_turnover": 63354221.55, "today_total_amount": None, "today_buy_amount": None, "today_sell_amount": None, "today_buy_qty": None, "today_sell_qty": None},
    {"code": "53", "name": "Investment Management Nepal Pvt. Ltd.", "phone": "4256589", "districts": ["Kathmandu", "Baglung"], "tms_link": "tms53.nepsetms.com.np", "branch_count": 2, "active_status": "A", "is_dealer": False, "avg_rating": 4.67, "total_ratings": 3, "thirty_days_turnover": 1361044098.82, "latest_turnover": 39040412.480000004, "today_total_amount": None, "today_buy_amount": None, "today_sell_amount": None, "today_buy_qty": None, "today_sell_qty": None},
    {"code": "54", "name": "Sewa Securities Pvt. Ltd.", "phone": "4256642", "districts": ["Kathmandu", "Makwanpur"], "tms_link": "tms54.nepsetms.com.np", "branch_count": 2, "active_status": "A", "is_dealer": False, "avg_rating": 4.5, "total_ratings": 8, "thirty_days_turnover": 923283558.91, "latest_turnover": 37998507.599999994, "today_total_amount": None, "today_buy_amount": None, "today_sell_amount": None, "today_buy_qty": None, "today_sell_qty": None},
    {"code": "55", "name": "Bhrikuti Stock Broking Co. Pvt. Ltd.", "phone": "4223466", "districts": ["Kathmandu", "Sunsari", "Parsa", "Dolkha", "Mahottari", "Kavrepalanchowk", "Surkhet", "Myagdi"], "tms_link": "tms55.nepsetms.com.np", "branch_count": 8, "active_status": "SUSPEND", "is_dealer": False, "avg_rating": 4.5, "total_ratings": 10, "thirty_days_turnover": 0, "latest_turnover": 0, "today_total_amount": None, "today_buy_amount": None, "today_sell_amount": None, "today_buy_qty": None, "today_sell_qty": None},
    {"code": "56", "name": "Sri Hari Securities Pvt. Ltd.", "phone": "4437562", "districts": ["Kathmandu", "Jhapa"], "tms_link": "tms56.nepsetms.com.np", "branch_count": 2, "active_status": "A", "is_dealer": False, "avg_rating": 4, "total_ratings": 10, "thirty_days_turnover": 4409637950.09, "latest_turnover": 96308652.2, "today_total_amount": None, "today_buy_amount": None, "today_sell_amount": None, "today_buy_qty": None, "today_sell_qty": None},
    {"code": "57", "name": "Aryatara Investment & Securities", "phone": "4233596", "districts": ["Kathmandu", "Rupandehi", "Dang", "Palpa", "Bhaktapur"], "tms_link": "tms57.nepsetms.com.np", "branch_count": 6, "active_status": "A", "is_dealer": False, "avg_rating": 2.78, "total_ratings": 18, "thirty_days_turnover": 6069424951.45, "latest_turnover": 156746120.5, "today_total_amount": None, "today_buy_amount": None, "today_sell_amount": None, "today_buy_qty": None, "today_sell_qty": None},
    {"code": "58", "name": "Naasa Securities Co. Ltd.", "phone": "01-4440384", "districts": ["Kathmandu", "Parsa", "Dhanusa", "Kaski"], "tms_link": "tms58.nepsetms.com.np", "branch_count": 4, "active_status": "A", "is_dealer": False, "avg_rating": 3.47, "total_ratings": 86, "thirty_days_turnover": 19856173949.55, "latest_turnover": 569045836.04, "today_total_amount": 569045836.04, "today_buy_amount": 302984941.02, "today_sell_amount": 266060895.02, "today_buy_qty": 620109, "today_sell_qty": 490189},
    {"code": "59", "name": "Deevyaa Securities & Stock House Pvt. Ltd", "phone": "01-4421488", "districts": ["Kathmandu", "Baglung", "Parbat"], "tms_link": "tms59.nepsetms.com.np", "branch_count": 3, "active_status": "A", "is_dealer": False, "avg_rating": 5, "total_ratings": 2, "thirty_days_turnover": 3095152000.39, "latest_turnover": 73730984.82, "today_total_amount": None, "today_buy_amount": None, "today_sell_amount": None, "today_buy_qty": None, "today_sell_qty": None},
    {"code": "60", "name": "Nagarik Stock Dealer ", "phone": "9851000000", "districts": ["Kathmandu"], "tms_link": "nsd.nepsetms.com.np", "branch_count": 1, "active_status": "A", "is_dealer": True, "avg_rating": 5, "total_ratings": 0, "thirty_days_turnover": 3097957362.89, "latest_turnover": 50125357.8, "today_total_amount": None, "today_buy_amount": None, "today_sell_amount": None, "today_buy_qty": None, "today_sell_qty": None},
    {"code": "61", "name": "BHOLE GANESH SECURITIES LTD", "phone": "9847083952", "districts": ["Kathmandu"], "tms_link": "tms61.nepsetms.com.np", "branch_count": 1, "active_status": "A", "is_dealer": False, "avg_rating": 5, "total_ratings": 1, "thirty_days_turnover": 255812185.7, "latest_turnover": 6420378.199999999, "today_total_amount": None, "today_buy_amount": None, "today_sell_amount": None, "today_buy_qty": None, "today_sell_qty": None},
    {"code": "62", "name": "Capital Max Securities Ltd", "phone": "9851097632", "districts": ["Kathmandu", "Kaski"], "tms_link": "tms62.nepsetms.com.np", "branch_count": 2, "active_status": "A", "is_dealer": False, "avg_rating": 5, "total_ratings": 8, "thirty_days_turnover": 5495074448.23, "latest_turnover": 165346071.46, "today_total_amount": None, "today_buy_amount": None, "today_sell_amount": None, "today_buy_qty": None, "today_sell_qty": None},
    {"code": "63", "name": "Himalayan Brokerage Company Limited", "phone": "9851055216", "districts": ["Kathmandu"], "tms_link": "tms63.nepsetms.com.np", "branch_count": 1, "active_status": "A", "is_dealer": False, "avg_rating": 3, "total_ratings": 2, "thirty_days_turnover": 2865706787.77, "latest_turnover": 78923722.7, "today_total_amount": None, "today_buy_amount": None, "today_sell_amount": None, "today_buy_qty": None, "today_sell_qty": None},
    {"code": "64", "name": "SUN SECURITIES PVT LTD", "phone": "9851333777", "districts": ["Kathmandu"], "tms_link": "tms64.nepsetms.com.np", "branch_count": 1, "active_status": "A", "is_dealer": False, "avg_rating": 5, "total_ratings": 18, "thirty_days_turnover": 3395396733.2, "latest_turnover": 155538923.7, "today_total_amount": None, "today_buy_amount": None, "today_sell_amount": None, "today_buy_qty": None, "today_sell_qty": None},
    {"code": "65", "name": "Sharepro Securities Private Limited", "phone": "9851122347", "districts": ["Kathmandu"], "tms_link": "tms65.nepsetms.com.np", "branch_count": 1, "active_status": "A", "is_dealer": False, "avg_rating": 5, "total_ratings": 3, "thirty_days_turnover": 2386390482.9, "latest_turnover": 118354603.9, "today_total_amount": None, "today_buy_amount": None, "today_sell_amount": None, "today_buy_qty": None, "today_sell_qty": None},
    {"code": "66", "name": "Miyo Securities Pvt Ltd", "phone": "9801881325", "districts": ["Kathmandu"], "tms_link": "tms66.nepsetms.com.np", "branch_count": 1, "active_status": "A", "is_dealer": False, "avg_rating": 5, "total_ratings": 0, "thirty_days_turnover": 1869743721.72, "latest_turnover": 21435845, "today_total_amount": None, "today_buy_amount": None, "today_sell_amount": None, "today_buy_qty": None, "today_sell_qty": None},
    {"code": "67", "name": "Property Wiard Limited", "phone": "9851349930", "districts": ["Kathmandu"], "tms_link": "tms67.nepsetms.com.np", "branch_count": 1, "active_status": "A", "is_dealer": False, "avg_rating": 5, "total_ratings": 0, "thirty_days_turnover": 1444773095.08, "latest_turnover": 28041059.299999997, "today_total_amount": None, "today_buy_amount": None, "today_sell_amount": None, "today_buy_qty": None, "today_sell_qty": None},
    {"code": "68", "name": "Elite Stock House Limited", "phone": "9851046054", "districts": [], "tms_link": "tms68.nepsetms.com.np", "branch_count": 0, "active_status": "A", "is_dealer": False, "avg_rating": 5, "total_ratings": 1, "thirty_days_turnover": 675369419, "latest_turnover": 30932346.5, "today_total_amount": None, "today_buy_amount": None, "today_sell_amount": None, "today_buy_qty": None, "today_sell_qty": None},
    {"code": "69", "name": "INDEX SECURITIES LIMITED", "phone": "9767245316", "districts": [], "tms_link": "tms69.nepsetms.com.np", "branch_count": 0, "active_status": "A", "is_dealer": False, "avg_rating": 5, "total_ratings": 0, "thirty_days_turnover": 1508673528.1, "latest_turnover": 18815055.6, "today_total_amount": None, "today_buy_amount": None, "today_sell_amount": None, "today_buy_qty": None, "today_sell_qty": None},
    {"code": "70", "name": "Infinity Securities Limited", "phone": "9851351802", "districts": [], "tms_link": "tms70.nepsetms.com.np", "branch_count": 0, "active_status": "A", "is_dealer": False, "avg_rating": 5, "total_ratings": 0, "thirty_days_turnover": 1385637225.2, "latest_turnover": 37961561.599999994, "today_total_amount": None, "today_buy_amount": None, "today_sell_amount": None, "today_buy_qty": None, "today_sell_qty": None},
    {"code": "71", "name": "SHUBHAKAMANA SECURITIES PVT. LTD", "phone": "9852027296", "districts": ["Morang"], "tms_link": "tms71.nepsetms.com.np", "branch_count": 1, "active_status": "A", "is_dealer": False, "avg_rating": 5, "total_ratings": 1, "thirty_days_turnover": 1974278393.27, "latest_turnover": 43707332.6, "today_total_amount": None, "today_buy_amount": None, "today_sell_amount": None, "today_buy_qty": None, "today_sell_qty": None},
    {"code": "72", "name": "Hatemalo Financial Services Private Limited", "phone": "9851112907", "districts": [], "tms_link": "tms72.nepsetms.com.np", "branch_count": 0, "active_status": "A", "is_dealer": False, "avg_rating": 2.33, "total_ratings": 3, "thirty_days_turnover": 889106572.2, "latest_turnover": 16644608.2, "today_total_amount": None, "today_buy_amount": None, "today_sell_amount": None, "today_buy_qty": None, "today_sell_qty": None},
    {"code": "73", "name": "Money World Share Exchange PVT Ltd", "phone": "9849892892", "districts": [], "tms_link": "tms73.nepsetms.com.np", "branch_count": 0, "active_status": "A", "is_dealer": False, "avg_rating": 5, "total_ratings": 0, "thirty_days_turnover": 459392.4, "latest_turnover": 92964, "today_total_amount": None, "today_buy_amount": None, "today_sell_amount": None, "today_buy_qty": None, "today_sell_qty": None},
    {"code": "74", "name": "KALASH STOCK MARKET PVT. LTD.", "phone": "9851254622", "districts": ["Rupandehi"], "tms_link": "tms74.nepsetms.com.np", "branch_count": 1, "active_status": "A", "is_dealer": False, "avg_rating": 4.5, "total_ratings": 4, "thirty_days_turnover": 4031271972.91, "latest_turnover": 277301131.5, "today_total_amount": 277301131.5, "today_buy_amount": 225546511.1, "today_sell_amount": 51754620.4, "today_buy_qty": 273868, "today_sell_qty": 89954},
    {"code": "75", "name": "N.I.M.B. Stock Markets Limited", "phone": "9851400375", "districts": [], "tms_link": "tms75.nepsetms.com.np", "branch_count": 0, "active_status": "A", "is_dealer": False, "avg_rating": 3.5, "total_ratings": 4, "thirty_days_turnover": 2688011779.34, "latest_turnover": 248955509.1, "today_total_amount": 248955509.1, "today_buy_amount": 49595236.9, "today_sell_amount": 199360272.2, "today_buy_qty": 104817, "today_sell_qty": 212354},
    {"code": "76", "name": "Machhapuchchhre Securities Limited", "phone": "9851106225", "districts": [], "tms_link": "tms76.nepsetms.com.np", "branch_count": 0, "active_status": "A", "is_dealer": False, "avg_rating": 5, "total_ratings": 0, "thirty_days_turnover": 383475889.71, "latest_turnover": 8212125.11, "today_total_amount": None, "today_buy_amount": None, "today_sell_amount": None, "today_buy_qty": None, "today_sell_qty": None},
    {"code": "77", "name": "Nabil Stock Dealer Ltd.", "phone": "9844760946", "districts": [], "tms_link": "tms77.nepsetms.com.np", "branch_count": 0, "active_status": "A", "is_dealer": True, "avg_rating": 4.83, "total_ratings": 6, "thirty_days_turnover": 6041738438.85, "latest_turnover": 224467408.1, "today_total_amount": 224467408.1, "today_buy_amount": 153330606.7, "today_sell_amount": 71136801.4, "today_buy_qty": 132519, "today_sell_qty": 41901},
    {"code": "78", "name": "Garima Securities Limited", "phone": "9841933097", "districts": [], "tms_link": "tms78.garimasecurities.com.np", "branch_count": 0, "active_status": "A", "is_dealer": False, "avg_rating": 5, "total_ratings": 0, "thirty_days_turnover": 316492220.21, "latest_turnover": 10467789.5, "today_total_amount": None, "today_buy_amount": None, "today_sell_amount": None, "today_buy_qty": None, "today_sell_qty": None},
    {"code": "79", "name": "pahiinvestment", "phone": "9866823055", "districts": [], "tms_link": "tms79.nepsetms.com.np", "branch_count": 0, "active_status": "A", "is_dealer": False, "avg_rating": 5, "total_ratings": 0, "thirty_days_turnover": 41792464.4, "latest_turnover": 2760111.9, "today_total_amount": None, "today_buy_amount": None, "today_sell_amount": None, "today_buy_qty": None, "today_sell_qty": None},
    {"code": "80", "name": "Indira securities pvt. ltd", "phone": "9851107444", "districts": ["Surkhet", "Kailali"], "tms_link": "tms80.nepsetms.com.np", "branch_count": 2, "active_status": "A", "is_dealer": False, "avg_rating": 5, "total_ratings": 0, "thirty_days_turnover": 1222026075.36, "latest_turnover": 30279796.7, "today_total_amount": None, "today_buy_amount": None, "today_sell_amount": None, "today_buy_qty": None, "today_sell_qty": None},
    {"code": "81", "name": "Aakashbhairab Securities Ltd.", "phone": "9851027899", "districts": [], "tms_link": "tms81.nepsetms.com.np", "branch_count": 0, "active_status": "A", "is_dealer": False, "avg_rating": 5, "total_ratings": 0, "thirty_days_turnover": 2005773164.1, "latest_turnover": 44432050.599999994, "today_total_amount": None, "today_buy_amount": None, "today_sell_amount": None, "today_buy_qty": None, "today_sell_qty": None},
    {"code": "82", "name": "N.M.B. SECURITIES LIMITED", "phone": "9852024863", "districts": [], "tms_link": "tms82.nepsetms.com.np", "branch_count": 0, "active_status": "A", "is_dealer": False, "avg_rating": 5, "total_ratings": 0, "thirty_days_turnover": 1205898827.6, "latest_turnover": 20468691.2, "today_total_amount": None, "today_buy_amount": None, "today_sell_amount": None, "today_buy_qty": None, "today_sell_qty": None},
    {"code": "83", "name": "Sanima Securities Limited", "phone": "9851128311", "districts": [], "tms_link": "tms83.nepsetms.com.np", "branch_count": 0, "active_status": "A", "is_dealer": False, "avg_rating": 5, "total_ratings": 0, "thirty_days_turnover": 1103406313.35, "latest_turnover": 25718277, "today_total_amount": None, "today_buy_amount": None, "today_sell_amount": None, "today_buy_qty": None, "today_sell_qty": None},
    {"code": "84", "name": "MILKY WAY SHARE BROKER COMPANY LTD ", "phone": "9840899480", "districts": [], "tms_link": "tms84.nepsetms.com.np", "branch_count": 0, "active_status": "A", "is_dealer": False, "avg_rating": 2, "total_ratings": 1, "thirty_days_turnover": 1309742047.31, "latest_turnover": 30624276.4, "today_total_amount": None, "today_buy_amount": None, "today_sell_amount": None, "today_buy_qty": None, "today_sell_qty": None},
    {"code": "85", "name": "Capital Hub P. Ltd", "phone": "9851020334", "districts": [], "tms_link": "tms85.nepsetms.com.np", "branch_count": 0, "active_status": "A", "is_dealer": False, "avg_rating": 5, "total_ratings": 1, "thirty_days_turnover": 914298676.82, "latest_turnover": 21665173.3, "today_total_amount": None, "today_buy_amount": None, "today_sell_amount": None, "today_buy_qty": None, "today_sell_qty": None},
    {"code": "86", "name": "Stoxkarts Securities Limited", "phone": "9851144940", "districts": [], "tms_link": "tms86.nepsetms.com.np", "branch_count": 0, "active_status": "A", "is_dealer": False, "avg_rating": 3.5, "total_ratings": 2, "thirty_days_turnover": 695125160.4, "latest_turnover": 13931101.5, "today_total_amount": None, "today_buy_amount": None, "today_sell_amount": None, "today_buy_qty": None, "today_sell_qty": None},
    {"code": "87", "name": "S.P.S.A. Securities Limited", "phone": "9851226859", "districts": [], "tms_link": "tms87.nepsetms.com.np", "branch_count": 0, "active_status": "A", "is_dealer": False, "avg_rating": 5, "total_ratings": 2, "thirty_days_turnover": 1443587677.55, "latest_turnover": 57966339.8, "today_total_amount": None, "today_buy_amount": None, "today_sell_amount": None, "today_buy_qty": None, "today_sell_qty": None},
    {"code": "88", "name": "Blue Chip Securities Ltd", "phone": "9851040252", "districts": [], "tms_link": "tms88.nepsetms.com.np", "branch_count": 0, "active_status": "A", "is_dealer": False, "avg_rating": 5, "total_ratings": 0, "thirty_days_turnover": 2226185634.3, "latest_turnover": 40761590.7, "today_total_amount": None, "today_buy_amount": None, "today_sell_amount": None, "today_buy_qty": None, "today_sell_qty": None},
    {"code": "89", "name": "Global IME Securities Limited", "phone": "9841661185", "districts": [], "tms_link": "tms89.nepsetms.com.np", "branch_count": 0, "active_status": "A", "is_dealer": False, "avg_rating": 5, "total_ratings": 5, "thirty_days_turnover": 2754934670.55, "latest_turnover": 9806599.7, "today_total_amount": None, "today_buy_amount": None, "today_sell_amount": None, "today_buy_qty": None, "today_sell_qty": None},
    {"code": "90", "name": "Sajilo Broker Limited", "phone": "9841387829", "districts": [], "tms_link": "tms90.nepsetms.com.np", "branch_count": 0, "active_status": "A", "is_dealer": False, "avg_rating": 1, "total_ratings": 1, "thirty_days_turnover": 526623276.9, "latest_turnover": 11081885.8, "today_total_amount": None, "today_buy_amount": None, "today_sell_amount": None, "today_buy_qty": None, "today_sell_qty": None},
    {"code": "91", "name": "Citizens Share Broker Limited", "phone": "9766381154", "districts": ["Rupandehi"], "tms_link": "tms91.nepsetms.com.np", "branch_count": 1, "active_status": "A", "is_dealer": False, "avg_rating": 4.5, "total_ratings": 2, "thirty_days_turnover": 1744764849.11, "latest_turnover": 48983129.8, "today_total_amount": None, "today_buy_amount": None, "today_sell_amount": None, "today_buy_qty": None, "today_sell_qty": None},
    {"code": "92", "name": "Roadshow securities limited", "phone": "9851224167", "districts": [], "tms_link": "tms92.nepsetms.com.np", "branch_count": 0, "active_status": "A", "is_dealer": False, "avg_rating": 5, "total_ratings": 0, "thirty_days_turnover": 1598949179.15, "latest_turnover": 23238644.8, "today_total_amount": None, "today_buy_amount": None, "today_sell_amount": None, "today_buy_qty": None, "today_sell_qty": None},
    {"code": "93", "name": "Beni Securities Pvt.Ltd.", "phone": "9841309269", "districts": [], "tms_link": "tms93.nepsetms.com.np", "branch_count": 0, "active_status": "A", "is_dealer": False, "avg_rating": 5, "total_ratings": 0, "thirty_days_turnover": 32953774.4, "latest_turnover": 3576567.4, "today_total_amount": None, "today_buy_amount": None, "today_sell_amount": None, "today_buy_qty": None, "today_sell_qty": None},
    {"code": "94", "name": "K.B.L. Securities Limited ", "phone": "9851076533", "districts": [], "tms_link": "tms94.nepsetms.com.np", "branch_count": 0, "active_status": "A", "is_dealer": False, "avg_rating": 4.5, "total_ratings": 4, "thirty_days_turnover": 1406211423.67, "latest_turnover": 30828169.700000003, "today_total_amount": None, "today_buy_amount": None, "today_sell_amount": None, "today_buy_qty": None, "today_sell_qty": None},
    {"code": "95", "name": "Magnet Securities and Investment Company Private Limited", "phone": "9851170069", "districts": ["Siraha"], "tms_link": "tms95.nepsetms.com.np", "branch_count": 1, "active_status": "A", "is_dealer": False, "avg_rating": 5, "total_ratings": 0, "thirty_days_turnover": 1197357059.9, "latest_turnover": 24676767, "today_total_amount": None, "today_buy_amount": None, "today_sell_amount": None, "today_buy_qty": None, "today_sell_qty": None},
    {"code": "96", "name": "Himalayan Securities Limited", "phone": "9851288045", "districts": [], "tms_link": "tms96.nepsetms.com.np", "branch_count": 0, "active_status": "A", "is_dealer": False, "avg_rating": 4.5, "total_ratings": 2, "thirty_days_turnover": 1138653155.55, "latest_turnover": 34571391.4, "today_total_amount": None, "today_buy_amount": None, "today_sell_amount": None, "today_buy_qty": None, "today_sell_qty": None},
    {"code": "97", "name": "R.B.B. Securities Company Ltd", "phone": "9851364896", "districts": [], "tms_link": "tms97.nepsetms.com.np", "branch_count": 0, "active_status": "A", "is_dealer": False, "avg_rating": 2, "total_ratings": 2, "thirty_days_turnover": 618944245.9, "latest_turnover": 4049990.7, "today_total_amount": None, "today_buy_amount": None, "today_sell_amount": None, "today_buy_qty": None, "today_sell_qty": None},
    {"code": "98", "name": "Trademow Securities Private Limited", "phone": "9851119274", "districts": [], "tms_link": "tms98.trademow.com", "branch_count": 0, "active_status": "A", "is_dealer": False, "avg_rating": 5, "total_ratings": 0, "thirty_days_turnover": 374838786.95, "latest_turnover": 6198684, "today_total_amount": None, "today_buy_amount": None, "today_sell_amount": None, "today_buy_qty": None, "today_sell_qty": None},
    {"code": "99", "name": "Prabhu Stock Market Limited", "phone": "9851062359", "districts": [], "tms_link": "tms99.nepsetms.com.np", "branch_count": 0, "active_status": "A", "is_dealer": False, "avg_rating": 3, "total_ratings": 2, "thirty_days_turnover": 1621240111.39, "latest_turnover": 35868690.9, "today_total_amount": None, "today_buy_amount": None, "today_sell_amount": None, "today_buy_qty": None, "today_sell_qty": None},
    {"code": "100", "name": "Sunrise Securities Limited", "phone": "9767983247", "districts": [], "tms_link": None, "branch_count": 0, "active_status": "A", "is_dealer": False, "avg_rating": 5, "total_ratings": 0, "thirty_days_turnover": 2626819601.39, "latest_turnover": 45385157.599999994, "today_total_amount": None, "today_buy_amount": None, "today_sell_amount": None, "today_buy_qty": None, "today_sell_qty": None},
    {"code": "101", "name": "APPLE SECURITIES PRIVATE LIMITED", "phone": "9849389621", "districts": [], "tms_link": None, "branch_count": 0, "active_status": "A", "is_dealer": False, "avg_rating": 5, "total_ratings": 0, "thirty_days_turnover": 4183825005.5, "latest_turnover": 62117640.199999996, "today_total_amount": None, "today_buy_amount": None, "today_sell_amount": None, "today_buy_qty": None, "today_sell_qty": None},
]


def search_brokers(query: str) -> list[dict]:
    q = query.strip().lower()
    if not q:
        return BROKERS[:20]
    results = []
    for b in BROKERS:
        if q in b['name'].lower() or b['code'].startswith(q):
            results.append(b)
        elif any(q in d.lower() for d in b.get('districts', [])):
            results.append(b)
        elif q in b.get('phone', '').replace('-', '').replace(' ', ''):
            results.append(b)
        if len(results) >= 30:
            break
    return results[:30]


def get_top_brokers(period: str = 'monthly', limit: int = 20) -> list[dict]:
    if period == 'daily':
        key = 'latest_turnover'
    elif period == 'weekly':
        key = 'weekly_turnover'
        enriched = []
        for b in BROKERS:
            copy = dict(b)
            copy['weekly_turnover'] = (b.get('thirty_days_turnover', 0) or 0) / 4.3
            enriched.append(copy)
        sorted_brokers = sorted(enriched, key=lambda b: b.get(key, 0) or 0, reverse=True)
        return [{'rank': i+1, **b} for i, b in enumerate(sorted_brokers[:limit])]
    else:
        key = 'thirty_days_turnover'
    sorted_brokers = sorted(BROKERS, key=lambda b: b.get(key, 0) or 0, reverse=True)
    return [{'rank': i+1, **b} for i, b in enumerate(sorted_brokers[:limit])]
